### ISSUE TITLE
FEAT: Fetch voices and save them to store

### ISSUE THREAD

**Issue by o-nedashkivska** [BinaryStudioAcademy/bsa-2024-outreachvids#204]
### What feature?

When user opens `scripts` tab on video-menu, a list of voices must be fetched and saved to store. When request is in progress show loader.

Use branch from [azure text to speech pr](https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/185) as your base branch.

**Comment by DaniellaZambrano** [comment]
It seems like they aren't being saved when I close the window and reopen it because of the logo that appears

Steps to reproduce:

1. Open the studio page
2. Click on "Scripts"
3. Click on "+" to add a script
4. Select "Voices" (all available voices are displayed)
5. Download at least one voice
6. Close the window and reopen it, and verify that the previously downloaded voice still shows the download symbol as if it wasn’t downloaded.

![Image](https://github.com/user-attachments/assets/025af409-1f24-4804-82a9-cc131d4e6acc)

**Comment by DaniellaZambrano** [comment]
@JKaypa
