### ISSUE TITLE
FEAT: Sign Up flow

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-2024-outreachvids#4]
### What feature?

- [x]  Add /sign-up route
- [x]  Add sign-up form
- [x]  Add sign-up action flow
- [x]  After form submission, the user is redirected to the app /
- [x]  Save an authenticated user to the redux store
- [x]  Add form validation
- [x]  "Log in" link should navigate to the Sign In page

P.S. Sign In/Sing Up pages can use one layout

### Add screenshots

![image](https://github.com/user-attachments/assets/59a31f2c-d5d2-4d37-93d3-4b293440af67)

**Comment by DaniellaZambrano** [comment]
There is a visual issue the first time I type in the "Repeat Password" field: another eye icon appears, which is duplicated, and the color and shape are incorrect. This needs to be fixed

Steps to reproduce the issue:
1. Open http://localhost:3000/sign-up
2. Fill the "Repeat Password" field, since the first word the icon appears

Image with the issue: 
![Image](https://github.com/user-attachments/assets/31958fc0-3a45-416c-aa06-6cdf07f1470d)

**Comment by DaniellaZambrano** [comment]
@lfelix3011 I'll be waiting for your response, thanks!

**Comment by lfelix3011** [comment]
@DaniellaZambrano Thanks for the review, and QA, doing an amazing job looking for all the details and requirements.

I thinks that may be due to the browser, IE and Edge has a build in show and hide for input type password, but Firefox and Chrome don't have it.

If the theory is correct it should happens for all the inputs type password for that specific browser. Even though, tomorrow i will be confirming this, you can check the images that were taken when the task was completed in the link to the pull request below.

https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/20

Note: When the images was capture I was using Chrome

**Comment by DaniellaZambrano** [comment]
Yes you're right I forgot to put my browser sorry, I already update it

**Comment by lfelix3011** [comment]
@DaniellaZambrano Here is the implementation to hide the default reveal icon

![Image](https://github.com/user-attachments/assets/a30fd111-3ddd-4597-99e4-a67a994b8066)

Here is the Pull Request https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/68

**Comment by DaniellaZambrano** [comment]
Hi @lfelix3011 , I don't think this message should be appears to an user 

![Image](https://github.com/user-attachments/assets/f3561676-4e2d-412b-992d-8080cba6e9d2)

**Comment by DaniellaZambrano** [comment]
@lfelix3011 Thanks for the feature at moment everything was ok!
